'use strict';

// tests for app
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('app', '/app.js', 'server');

describe('app', () => {
  before((done) => {
    done();
  });

  it('returns status code 200 with message', () => {
    return wrapped.run({}).then((response) => {
      expect(response.statusCode).to.equal(200);
      expect(response.body).to.be.equal('Hello, this is a serverless Autosense Backend!')
    });
  });

});
